seed: 42
train:
  max_seq_length: 4096
  global_batch_size: 128
  micro_batch_size: 4
  activation_checkpointing: true
  save_interval: 1000
  log_interval: 1
  lr_warmup_steps: 2000
  max_tokens: 3_000_000_000
eval:
  skip_validation: true
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 4e-4
    weight_decay: 0.1
    betas:
      - 0.9
      - 0.95
precision: bf16-mixed
num_nodes: 1

model_name: Qwen3-30B-A3B-Base
model_config:
  name: "Qwen3-30B-A3B"
  hf_config:
    org: "Qwen"
    name: "Qwen3-30B-A3B"
  block_size: 40960
  head_size: 128
  vocab_size: 151643
  padded_vocab_size: 151936
  n_layer: 48
  n_head: 32
  n_embd: 2048
  n_query_groups: 4
  rotary_percentage: 1.0
  parallel_residual: False
  bias: False
  norm_class_name: "RMSNorm"
  mlp_class_name: "LLaMAMoE"
  intermediate_size: 6144
  moe_intermediate_size: 768
  norm_eps: 1e-6
  rope_base: 1000000
  norm_qk: True
  n_expert: 128
  n_expert_per_token: 8
  n_safe_expert: 8
initial_checkpoint_dir: checkpoints/Qwen3-30B-A3B-Base
tokenizer_dir: checkpoints/Qwen3-30B-A3B-Base
out_dir: checkpoints/Qwen3-30B-A3B-Base-CPT-Safe

data:
  class_path: SafeData
  init_args:
    data_paths:
      - /mnt/shared-storage-gpfs2/wenxiaoyu-gpfs02/jincheng/data/qwen3/bio-forget-corpus
      - /mnt/shared-storage-gpfs2/wenxiaoyu-gpfs02/jincheng/data/qwen3/bio-retain-corpus
      - /mnt/shared-storage-gpfs2/wenxiaoyu-gpfs02/jincheng/data/qwen3/cyber-forget-corpus
      - /mnt/shared-storage-gpfs2/wenxiaoyu-gpfs02/jincheng/data/qwen3/cyber-retain-corpus
    weights:
      - 0.25
      - 0.25
      - 0.25
      - 0.25
    harmful_data_paths:
      - /mnt/shared-storage-gpfs2/wenxiaoyu-gpfs02/jincheng/data/qwen3/bio-forget-corpus
      - /mnt/shared-storage-gpfs2/wenxiaoyu-gpfs02/jincheng/data/qwen3/cyber-forget-corpus

logger_name: wandb
log:
  project: SafeMoE
  run: Qwen3-30B-A3B-Base-CPT-Safe